import type { Metadata } from "next";
import { Web3Providers } from "@/providers/web3";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen antialiased bg-[#0A0118]">
        <Web3Providers>
          <Header />
          {children}
          <Toaster />
        </Web3Providers>
      </body>
    </html>
  );
}
